<Project>

	<PropertyGroup>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Optimize>False</Optimize>
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<NoWarn>1701;1702;NU5104;NU1603;NU1900</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<Optimize>True</Optimize>
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<NoWarn>1701;1702;NU5104;NU1603;NU1900</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>$(MSBuildProjectName).Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>