<Project Sdk="MSTest.Sdk/4.2.3">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\mssql-database-scripts\CreateTables.sql" Link="CreateTables.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\mssql-database-scripts\SeedTables.sql" Link="SeedTables.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PersonenVerwaltung.ServiceApp\PersonenVerwaltung.ServiceApp.csproj" />
    <ProjectReference Include="..\..\src\PersonenVerwaltung.ServiceClient\PersonenVerwaltung.ServiceClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="SeedTables.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="18.10.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter" Version="4.4.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework" Version="4.4.1" />
  </ItemGroup>

</Project>
